### ISSUE TITLE
sort inside  Subject  page

### ISSUE THREAD

**Issue by AviHafner** [michael-maltsev/technion-histograms#1]
Hello Michal

I am the one who maintains the upgrade system today
And on the students' side it's called grades

### Your site is a helpful site
In my opinion, on the presentation page of each subject, the sorting of the semesters should have the dates reversed
That is, the last semesters should appear first

**Comment by michael-maltsev** [comment]
Hi Avi,

> Your site is a helpful site

Thank you. It would be more helpful if there was a way to get all the histograms from Technion without having to sign up to the relevant courses. Right now, this repository of histograms depends on students sharing the histograms that they can access, and so it will always be partial and outdated to some degree.

If you can help with this and provide me with the relevant API, database access, or anything else, that will help many students who benefit from this data.

> In my opinion, on the presentation page of each subject, the sorting of the semesters should have the dates reversed

Thank you for the feedback, but [this website](https://michael-maltsev.github.io/technion-histograms/) wasn't designed to be convenient. It's just a simple page with raw data. The main use for the histograms is to be browsed in [CheeseFork](https://cheesefork.cf/). See the screenshot below.

![image](https://user-images.githubusercontent.com/36999014/194852136-c2216648-a155-420a-80fb-69527c32c427.png)
